M48
; DRILL file {KiCad (7.0.0)} date Sat Mar 11 20:41:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-11T20:41:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.45Y2.24
X0.45Y2.16
X0.65Y2.2
T2
X0.1575Y2.2047
X0.1575Y0.1575
X1.4173Y2.2047
X1.4173Y0.1575
T0
M30
